version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/sites-enabled/myself
      - ./docs/.vitepress/dist:/myblog
  