name: Deploy To Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn
        yarn run build
    - name: deploy file to server
      uses: easingthemes/ssh-deploy@v2.0.7
      with:
        username: 'root'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: true
        source: './docs/.vitepress/dist/*'
        target: "~/source/myself/dist/"